name: .NET 2.2 CD

on:
  release:
    types:
      - created

jobs:
  deploy:
    name: Push package
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        working-directory: AccuRanker
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache NuGet packages
        uses: actions/cache@v4.0.0
        with:
          path: ~/.nuget/packages # Mac/Linux
          key: ${{ hashFiles('*/packages.lock.json') }}

      - name: Setup .NET Core SDK & nuget.config
        uses: actions/setup-dotnet@v1
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.REGISTRY_AUTH_WRITE_TOKEN }}
        with:
          dotnet-version: 3.1.x
          source-url: https://nuget.pkg.github.com/dentsudatalab/index.json

      - name: Get version number & set in env
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: echo "VERSION=$(echo "$TAG_NAME" | cut -c 2- )" >> $GITHUB_ENV

      - name: Pack project
        run: dotnet pack --configuration Release -p:PackageVersion=$VERSION

      - name: Push NuGet package
        run: curl -vX PUT -u "$GITHUB_ACTOR:${{ secrets.REGISTRY_AUTH_WRITE_TOKEN }}" -F package=@bin/Release/DentsuDataLab.AccuRanker.$VERSION.nupkg https://nuget.pkg.github.com/dentsudatalab/
