name: Create Release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1

      - name: Get tag & set as env
        run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create Release
        uses: actions/create-release@v1.1.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: $VERSION
          release_name: $VERSION
